import type { Metadata } from "next";
import { Oxanium } from "next/font/google";
import "./globals.css";

const oxanium = Oxanium({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Munir NFT Next.JS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-slate-900 ligh text-white ${oxanium.className}`}>
        {children}
      </body>
    </html>
  );
}
